# -*- coding: utf-8 -*-
"""final-exam

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tbws0TVVoa8KpBjvGXDmmyWDFRAXAopx
"""

import pandas as pd
data=pd.read_csv("/content/Mall_Customers.csv")
print(data.head())

import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
data=pd.read_csv("/content/Mall_Customers.csv")
data.head(6)

x = data.iloc[:, [3, 4]].values
wcss_list = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init="k-means++", random_state=42)
    kmeans.fit(x)
    wcss_list.append(kmeans.inertia_)

plt.plot(range(1, 11), wcss_list)
plt.title('the elbow method')
plt.xlabel("wcss_list")
plt.ylabel("frequency")
plt.show()

kmeans=KMeans(n_clusters=5,init="k-means++",random_state=42)
y_perd=kmeans.fit_predict(x)
print(y_perd)
plt.scatter(x[y_perd==0,0],x[y_perd==0,1],s=100,c="red",label="Cluster1")
plt.scatter(x[y_perd==1,0],x[y_perd==1,1],s=100,c="blue",label="Cluster 2")
plt.scatter(x[y_perd==2,0],x[y_perd==2,1],s=100,c="green",label="Cluster 3")
plt.scatter(x[y_perd==3,0],x[y_perd==3,1],s=100,c="cyan",label="Cluster 4")
plt.scatter(x[y_perd==4,0],x[y_perd==4,1],s=100,c="magenta",label="Cluster 5")
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],
s=300,c="yellow",label="Centroid")
plt.show()

